version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PORT: 8000
    networks:
      - app-tier
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - app-tier
    environment:
      MYSQL_DATABASE: 'hndb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'

    expose:
      # Opens port 3306 on the container
      - '3306'